server:
  port: 8080
spring:
  security:
    user:
      name: "Cee"   
      password: "1234"
  datasource:
    url: jdbc:mysql://localhost:3306/employeedb
    username: root
    password: Mysql@254
  application:
    name: product-service
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update