server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employeedb
    username: root
    password: makutano
  application:
    name: product-service
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update